# Generated by Django 4.2.2 on 2023-06-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentID', models.PositiveIntegerField()),
                ('StudentName', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('College', models.CharField(max_length=100)),
                ('POS', models.CharField(max_length=100)),
                ('YOA', models.DateField()),
            ],
        ),
    ]
